### ISSUE TITLE
EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by Christilut** [sindresorhus/electron-store#112]
```
Error: EBUSY: resource busy or locked, rename 'C:\Users\user\AppData\Roaming\rekordcloud-companion-app\config.json.754582357' -> 'C:\Users\user\AppData\Roaming\rekordcloud-companion-app\config.json'
    at Object.renameSync (fs.js:609:3)
    at Function.writeFileSync [as sync] (C:\Users\user\AppData\Local\Programs\rekordcloud-companion-app\resources\app.asar\node_modules\write-file-atomic\index.js:244:8)
    at ElectronStore.set store [as store] (C:\Users\user\AppData\Local\Programs\rekordcloud-companion-app\resources\app.asar\node_modules\conf\index.js:277:19)
    at ElectronStore.set (C:\Users\user\AppData\Local\Programs\rekordcloud-companion-app\resources\app.asar\node_modules\conf\index.js:152:14)
```

I'm seeing this error happen rarely to a very small number of users.

Maybe similar problem as #103 ?

**Comment by sindresorhus** [comment]
Yes. Usually caused by some (crappy) anti-virus software on Windows...

**Comment by Christilut** [comment]
Makes sense... Anti virus is a real fun problem yeah...
