### ISSUE TITLE
I have problems with babel and webpack

### ISSUE THREAD

**Issue by Juninho-dev** [sindresorhus/electron-store#200]
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/junielfilappi/Desktop/javascript/cloud-invoice-2/src/services/store.ts: `import Store = require('electron-store')` is not supported by @babel/plugin-transform-typescript
Please consider using `import Store from 'electron-store';` alongside Typescript's --allowSyntheticDefaultImports option.
> 1 | import Store = require('electron-store');
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | const store = new Store();
  4 |
    at File.buildCodeFrameError (/Users/junielfilappi/Desktop/javascript/cloud-invoice-2/node_modules/@babel/core/lib/transformation/file/file.js:244:12)
    at NodePath.buildCodeFrameError (/Users/junielfilappi/Desktop/javascript/cloud-invoice-2/node_modules/@babel/traverse/lib/path/index.js:139:21)

**Comment by Juninho-dev** [comment]
electron_store__WEBPACK_IMPORTED_MODULE_2___default(...) is not a constructor

**Comment by Juninho-dev** [comment]
I've tried it in every way, but none works, I don't know if I need to configure something in babel or webpack, I'm using electron-boirplate

**Comment by mquevill** [comment]
I tried the following methods in simple electron-boilerplate code and both worked for me. I'm thinking it has something to do with other code or other settings in your project.
- `const Store = require('electron-store');` in [sindresorhus/electron-boilerplate](https://github.com/sindresorhus/electron-boilerplate)
- `import Store from 'electron-store';` in [szwacz/electron-boilerplate](https://github.com/szwacz/electron-boilerplate)

**Comment by lmick002** [comment]
@Juninho-dev I wonder if there is a configuration for typescript that's needed. @mquevill Looks like both demo projects are javascript and not typescript config. im running into the same issue now

**Comment by mquevill** [comment]
If you're using webpack v5, check your config for a `library` element as per https://hinty.io/devforth/fix-webpack-imported-module-is-not-a-function-for-webpack5/

It sounds like an issue with webpack configuration, not with this package. I was able to build [Devtography/electron-react-typescript-webpack-boilerplate](https://github.com/Devtography/electron-react-typescript-webpack-boilerplate) with no issues.

**Comment by Juninho-dev** [comment]
I managed to solve it, thanks!
