### ISSUE TITLE
Error: Cannot find module 'ajv-formats'

### ISSUE THREAD

**Issue by MetaiR** [sindresorhus/electron-store#207]
my app has been created with electron-forge and I got this error during electron startup:

```
App threw an error during load
Error: Cannot find module 'ajv-formats'
    at webpackMissingModule (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:6530:87)
    at Object.<anonymous> (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:6530:173)
    at Object../node_modules/conf/dist/source/index.js (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:6980:30)
    at __webpack_require__ (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:21:30)
    at Object../node_modules/electron-store/index.js (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:8141:14)
    at __webpack_require__ (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:21:30)
    at Object../src/util/db-util.ts (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:14092:40)
    at __webpack_require__ (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:21:30)
    at Object../src/main.ts (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:14026:17)
    at __webpack_require__ (F:\git\teacher_e-iac_encrypted\.webpack\main\index.js:21:30)
```

------------update-----------
looks like the problem is related to `yarn`
I run my app with npm and it fixed but I had this problem with yarn and yarn.lock

**Comment by ivancuric** [comment]
Same thing, electron-forge and yarn. Sadly I can't use npm since I'm getting errors with local paths (`file:` resolutions).

**Comment by franz-geiser** [comment]
Same problem for me.
Solved by removing node_modules.

**Comment by sindresorhus** [comment]
This is yarn hoisting plus webpack bundling `conf` and failing to include `ajv-formats`, not a bug in this package.

Keep `electron-store` external in the main-process build, or reinstall `node_modules` as above, and it resolves.
