### ISSUE TITLE
no space left on device error in windows system

### ISSUE THREAD

**Issue by stefanJi** [sindresorhus/electron-store#257]
```
Error: ENOSPC: no space left on device, open 'C:\Users\Administrator\AppData\Roaming\XX\config.json.tmp-37898232101397bd'
    at openSync (node:fs:585:3)
    at func (node:electron/js2c/asar_bundle:5:1812)
    at attempt (D:\XX\XX\resources\app.asar\node_modules\atomically\dist\utils\retryify.js:33:27)
    at Object.writeFileSync (D:\XX\resources\app.asar\node_modules\atomically\dist\index.js:136:49)
    at ElectronStore._write (D:\XX\resources\app.asar\node_modules\conf\dist\source\index.js:375:28)
    at set store [as store] (D:\XX\resources\app.asar\node_modules\conf\dist\source\index.js:296:14)
    at ElectronStore.set (D:\XX\resources\app.asar\node_modules\conf\dist\source\index.js:189:20)
```

**Comment by sindresorhus** [comment]
The error says it all:

> no space left on device
