### ISSUE TITLE
Error: EEXIST: file already exists, mkdir 'C:\Users\<user>\AppData\Roaming\Electron'

### ISSUE THREAD

**Issue by Superior126** [sindresorhus/electron-store#267]
Im having an issue where my electron app wont start because of this error: 
```powershell
[1] Error: EEXIST: file already exists, mkdir 'C:\Users\<user>\AppData\Roaming\Electron'
[1]     at mkdirSync (fs.js:731:3)
[1]     at Object.fs.mkdirSync (ELECTRON_ASAR.js:721:16)
[1]     at ElectronStore._ensureDirectory (C:\Users\<user>\Documents\GitHub\Ringer-Client-Desktop\node_modules\conf\dist\source\index.js:358:12)
[1]     at ElectronStore.get store [as store] (C:\Users\<user>\Documents\GitHub\Ringer-Client-Desktop\node_modules\conf\dist\source\index.js:284:22)
[1]     at new Conf (C:\Users\<user>\Documents\GitHub\Ringer-Client-Desktop\node_modules\conf\dist\source\index.js:131:32)
[1]     at new ElectronStore (C:\Users\<user>\Documents\GitHub\Ringer-Client-Desktop\node_modules\electron-store\index.js:69:3)
[1]     at Object.<anonymous> (C:\Users\<user>\Documents\GitHub\Ringer-Client-Desktop\main.js:12:15)
[1]     at Object.<anonymous> (C:\Users\<user>\Documents\GitHub\Ringer-Client-Desktop\main.js:135:3)
[1]     at Module._compile (internal/modules/cjs/loader.js:693:30)
[1]     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\<user>\Documents\GitHub\Ringer-Client-Desktop\node_modules\electron-compile\lib\require-hook.js:77:14)
```

### Platform Info

**OS:** Windows

**Version:** Windows 11 Home

**Comment by sindresorhus** [comment]
Current versions call `fs.mkdirSync(..., {recursive: true})`, which is a no-op when the directory already exists, so this is not reproducible now. Your trace also goes through `electron-compile`'s patched asar `fs`, which is unmaintained.

If you still see it on 11.0.2, check that `AppData\Roaming\Electron` is a directory and not a file.
