### ISSUE TITLE
Why require('electron-store') occur ...options  ^^^  SyntaxError: Unexpected token ...？in Electron-forge?

### ISSUE THREAD

**Issue by Iteravse** [sindresorhus/electron-store#77]
when i require('electron-store')  in Electron-forge main.js, it certainly show me these error,what's wrong?

`Active code page: 65001
√ Checking your system
√ Locating Application
√ Preparing native dependencies
√ Launching Application

App threw an error during load
D:\DownLoad\PortableGit\notepad\node_modules\electron-store\index.js:12
                        ...options
                        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.require.extensions.(anonymous function) [as .js] (D:\DownLoad\PortableGit\notepad\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\DownLoad\PortableGit\notepad\src\main.js:34:14)`

my electron version:v1.4.13
nodejs version:v10.16.0

**Comment by sindresorhus** [comment]
Open an issue on Electron-forge.
