### ISSUE TITLE
cwd: Can we specify the config file path to the same path of the Electron app?

### ISSUE THREAD

**Issue by cetorres** [sindresorhus/electron-store#90]
I'm creating a portable desktop app to run from a USB pen and I need to store the config file on the same path of the Electron app to keep the data inside the USB drive and work the same way in every computer the user plugs the USB drive and run the app from it.
Thank you.

**Comment by sindresorhus** [comment]
You could set `cwd` to `path.resolve('..', app.getAppPath())`.

https://electronjs.org/docs/api/app#appgetapppath

**Comment by sindresorhus** [comment]
I'm happy to add a tip to the readme about supporting portable apps, if you can confirm the above is working.

**Comment by cetorres** [comment]
Hi @sindresorhus, thank you for the answer.
I tried what you suggested. 
```Javascript
const appPath = path.resolve('..', app.getAppPath());
const store = new Store({ name: 'storage', fileExtension: 'db', cwd: appPath, encryptionKey: config.encryptionPass });
```
It works when debugging (yarn start), but it's not working when I create the app package (executable). It shows a Javascript alert with the following error:

```
Uncaught Exception:
Error: EEXIST: file already exists, mkdir '/Users/cetorres/Projects/red-key/redkey-electron/release/mac/RedKey.app/Contents/Resources/app.asar'
    at Object.mkdirSync (fs.js:764:3)
    at AsyncFunction.module.exports.sync (/Users/cetorres/Projects/red-key/redkey-electron/release/mac/RedKey.app/Contents/Resources/app.asar/node_modules/make-dir/index.js:108:6)
    at ElectronStore._ensureDirectory (/Users/cetorres/Projects/red-key/redkey-electron/release/mac/RedKey.app/Contents/Resources/app.asar/node_modules/conf/index.js:161:11)
    at ElectronStore.set store [as store] (/Users/cetorres/Projects/red-key/redkey-electron/release/mac/RedKey.app/Contents/Resources/app.asar/node_modules/conf/index.js:435:8)
    at ElectronStore.set (/Users/cetorres/Projects/red-key/redkey-electron/release/mac/RedKey.app/Contents/Resources/app.asar/node_modules/conf/index.js:316:14)
    at EventEmitter.<anonymous> (/Users/cetorres/Projects/red-key/redkey-electron/release/mac/RedKey.app/Contents/Resources/app.asar/main.js:133:9)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/Users/cetorres/Projects/red-key/redkey-electron/release/mac/RedKey.app/Contents/Resources/electron.asar/browser/api/web-contents.js:335:21)
    at WebContents.emit (events.js:200:13)
```

Do you have any other suggestions?
Thank you.

**Comment by malammar** [comment]
I'm having the same exact issue. Why was this closed?

**Comment by turdiyev** [comment]
I'm using `path.dirname(__dirname)` or `process.cwd()` for cwd.

```const config  = { name: 'storage', fileExtension: 'db', cwd: path.dirname(__dirname), encryptionKey: config.encryptionPass }
const store = new Store(config );
```

**Comment by jlw4049** [comment]
> You could set `cwd` to `path.resolve('..', app.getAppPath())`.
> 
> https://electronjs.org/docs/api/app#appgetapppath

This worked great. I know this is an older post but adding this to the guide would be nice.

**Comment by dingshaohua-com** [comment]
> Error: EEXIST: file already exists, mkdir '/Users/cetorres/Projects/red-key/redkey-electron/release/mac/RedKey.app/Contents/Resources/app.asar'

The answer is a bit late, I hope it can help those who come later
```js
const getResourcesPath = () => {
  if (app.isPackaged) {
    return process.resourcesPath;
  } else {
    return path.join(app.getAppPath(), "src");
  }
};

new Store({cwd: getResourcesPath()})
```
