### ISSUE TITLE
Syntax Error: Unexpected toekn ...

### ISSUE THREAD

**Issue by dlujan** [sindresorhus/electron-store#91]
Getting an error when I try to use electron-store.

App threw an error during load
[1] /Users/myname/Desktop/myapp/node_modules/electron-store/index.js:12
[1]                     ...options
[1]                     ^^^
[1]
[1] SyntaxError: Unexpected token ...
[1]     at createScript (vm.js:74:10)
[1]     at Object.runInThisContext (vm.js:116:10)
[1]     at Module._compile (module.js:533:28)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/myname/Desktop/myapp/public/DataStorage.js:1:170)

Has this happened to anyone and is there a way to fix it?

Thanks

**Comment by sindresorhus** [comment]
Seems like you're either running a very old Electron version or your build system does not support object spread syntax. This is not a problem with this package.

**Comment by dlujan** [comment]
I was running a very old Electron version. Thank you for bringing that up. I feel very dumb :)
